-- -----------------------------------------------------------------------------
-- OpenSi : Outils libres de gestion d'entreprise                             --
-- Copyright (C) 2003 Speedinfo.fr S.A.R.L.                                   --
-- Contact: contact@opensi.org                                                --
--                                                                            --
-- This program is free software; you can redistribute it and/or              --
-- modify it under the terms of the GNU General Public License                --
-- as published by the Free Software Foundation; either version 2             --
-- of the License, or (at your option) any later version.                     --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU General Public License for more details.                               --
--                                                                            --
-- You should have received a copy of the GNU General Public License          --
-- along with this program; if not, write to the Free Software                --
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. --
-- -----------------------------------------------------------------------------

-- Insertion des pays

insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AD', 'ANDORRE', 'ANDORRA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AE', 'ÉMIRATS ARABES UNIS', 'UNITED ARAB EMIRATES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AF', 'AFGHANISTAN', 'AFGHANISTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AG', 'ANTIGUA-ET-BARBUDA', 'ANTIGUA AND BARBUDA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AI', 'ANGUILLA', 'ANGUILLA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AL', 'ALBANIE', 'ALBANIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AM', 'ARMÉNIE', 'ARMENIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AN', 'ANTILLES NÉERLANDAISES', 'NETHERLANDS ANTILLES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AO', 'ANGOLA', 'ANGOLA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AQ', 'ANTARCTIQUE', 'ANTARCTICA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AR', 'ARGENTINE', 'ARGENTINA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AS', 'SAMOA AMÉRICAINES', 'AMERICAN SAMOA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AT', 'AUTRICHE', 'AUSTRIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AU', 'AUSTRALIE', 'AUSTRALIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AW', 'ARUBA', 'ARUBA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AX', 'ÅLAND, ÎLES', 'ÅLAND ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('AZ', 'AZERBAÏDJAN', 'AZERBAIJAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BA', 'BOSNIE-HERZÉGOVINE', 'BOSNIA AND HERZEGOVINA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BB', 'BARBADE', 'BARBADOS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BD', 'BANGLADESH', 'BANGLADESH', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BE', 'BELGIQUE', 'BELGIUM', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BF', 'BURKINA FASO', 'BURKINA FASO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BG', 'BULGARIE', 'BULGARIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BH', 'BAHREÏN', 'BAHRAIN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BI', 'BURUNDI', 'BURUNDI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BJ', 'BÉNIN', 'BENIN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BL', 'SAINT-BARTHÉLEMY', 'SAINT BARTHÉLEMY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BM', 'BERMUDES', 'BERMUDA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BN', 'BRUNÉI DARUSSALAM', 'BRUNEI DARUSSALAM', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BO', 'BOLIVIE', 'BOLIVIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BR', 'BRÉSIL', 'BRAZIL', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BS', 'BAHAMAS', 'BAHAMAS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BT', 'BHOUTAN', 'BHUTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BV', 'BOUVET, ÎLE', 'BOUVET ISLAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BW', 'BOTSWANA', 'BOTSWANA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BY', 'BÉLARUS', 'BELARUS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('BZ', 'BELIZE', 'BELIZE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CA', 'CANADA', 'CANADA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CC', 'COCOS (KEELING), ÎLES', 'COCOS (KEELING) ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CD', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CF', 'CENTRAFRICAINE, RÉPUBLIQUE', 'CENTRAL AFRICAN REPUBLIC', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CG', 'CONGO', 'CONGO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CH', 'SUISSE', 'SWITZERLAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CI', 'CÔTE D''IVOIRE', 'CÔTE D''IVOIRE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CK', 'COOK, ÎLES', 'COOK ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CL', 'CHILI', 'CHILE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CM', 'CAMEROUN', 'CAMEROON', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CN', 'CHINE', 'CHINA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CO', 'COLOMBIE', 'COLOMBIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CR', 'COSTA RICA', 'COSTA RICA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CU', 'CUBA', 'CUBA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CV', 'CAP-VERT', 'CAPE VERDE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CX', 'CHRISTMAS, ÎLE', 'CHRISTMAS ISLAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CY', 'CHYPRE', 'CYPRUS', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('CZ', 'TCHÈQUE, RÉPUBLIQUE', 'CZECH REPUBLIC', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('DE', 'ALLEMAGNE', 'GERMANY', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('DJ', 'DJIBOUTI', 'DJIBOUTI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('DK', 'DANEMARK', 'DENMARK', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('DM', 'DOMINIQUE', 'DOMINICA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('DO', 'DOMINICAINE, RÉPUBLIQUE', 'DOMINICAN REPUBLIC', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('DZ', 'ALGÉRIE', 'ALGERIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('EC', 'ÉQUATEUR', 'ECUADOR', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('EE', 'ESTONIE', 'ESTONIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('EG', 'ÉGYPTE', 'EGYPT', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('EH', 'SAHARA OCCIDENTAL', 'WESTERN SAHARA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ER', 'ÉRYTHRÉE', 'ERITREA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ES', 'ESPAGNE', 'SPAIN', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ET', 'ÉTHIOPIE', 'ETHIOPIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('FI', 'FINLANDE', 'FINLAND', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('FJ', 'FIDJI', 'FIJI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('FK', 'FALKLAND, ÎLES (MALVINAS)', 'FALKLAND ISLANDS (MALVINAS)', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('FM', 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE', 'MICRONESIA, FEDERATED STATES OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('FO', 'FÉROÉ, ÎLES', 'FAROE ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('FR', 'FRANCE', 'FRANCE', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GA', 'GABON', 'GABON', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GB', 'ROYAUME-UNI', 'UNITED KINGDOM', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GD', 'GRENADE', 'GRENADA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GE', 'GÉORGIE', 'GEORGIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GF', 'GUYANE FRANÇAISE', 'FRENCH GUIANA', 0, 'D');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GG', 'GUERNESEY', 'GUERNSEY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GH', 'GHANA', 'GHANA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GI', 'GIBRALTAR', 'GIBRALTAR', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GL', 'GROENLAND', 'GREENLAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GM', 'GAMBIE', 'GAMBIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GN', 'GUINÉE', 'GUINEA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GP', 'GUADELOUPE', 'GUADELOUPE', 0, 'D');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GQ', 'GUINÉE ÉQUATORIALE', 'EQUATORIAL GUINEA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GR', 'GRÈCE', 'GREECE', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GS', 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GT', 'GUATEMALA', 'GUATEMALA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GU', 'GUAM', 'GUAM', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GW', 'GUINÉE-BISSAU', 'GUINEA-BISSAU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('GY', 'GUYANA', 'GUYANA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('HK', 'HONG-KONG', 'HONG KONG', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('HM', 'HEARD, ÎLE ET MCDONALD, ÎLES', 'HEARD ISLAND AND MCDONALD ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('HN', 'HONDURAS', 'HONDURAS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('HR', 'CROATIE', 'CROATIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('HT', 'HAÏTI', 'HAITI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('HU', 'HONGRIE', 'HUNGARY', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ID', 'INDONÉSIE', 'INDONESIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IE', 'IRLANDE', 'IRELAND', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IL', 'ISRAËL', 'ISRAEL', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IM', 'ÎLE DE MAN', 'ISLE OF MAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IN', 'INDE', 'INDIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IO', 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L''', 'BRITISH INDIAN OCEAN TERRITORY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IQ', 'IRAQ', 'IRAQ', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IR', 'IRAN, RÉPUBLIQUE ISLAMIQUE D''', 'IRAN, ISLAMIC REPUBLIC OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IS', 'ISLANDE', 'ICELAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('IT', 'ITALIE', 'ITALY', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('JE', 'JERSEY', 'JERSEY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('JM', 'JAMAÏQUE', 'JAMAICA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('JO', 'JORDANIE', 'JORDAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('JP', 'JAPON', 'JAPAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KE', 'KENYA', 'KENYA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KG', 'KIRGHIZISTAN', 'KYRGYZSTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KH', 'CAMBODGE', 'CAMBODIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KI', 'KIRIBATI', 'KIRIBATI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KM', 'COMORES', 'COMOROS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KN', 'SAINT-KITTS-ET-NEVIS', 'SAINT KITTS AND NEVIS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KP', 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KR', 'CORÉE, RÉPUBLIQUE DE', 'KOREA, REPUBLIC OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KW', 'KOWEÏT', 'KUWAIT', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KY', 'CAÏMANES, ÎLES', 'CAYMAN ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('KZ', 'KAZAKHSTAN', 'KAZAKHSTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LA', 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LB', 'LIBAN', 'LEBANON', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LC', 'SAINTE-LUCIE', 'SAINT LUCIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LI', 'LIECHTENSTEIN', 'LIECHTENSTEIN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LK', 'SRI LANKA', 'SRI LANKA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LR', 'LIBÉRIA', 'LIBERIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LS', 'LESOTHO', 'LESOTHO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LT', 'LITUANIE', 'LITHUANIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LU', 'LUXEMBOURG', 'LUXEMBOURG', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LV', 'LETTONIE', 'LATVIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('LY', 'LIBYENNE, JAMAHIRIYA ARABE', 'LIBYAN ARAB JAMAHIRIYA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MA', 'MAROC', 'MOROCCO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MC', 'MONACO', 'MONACO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MD', 'MOLDOVA, RÉPUBLIQUE DE', 'MOLDOVA, REPUBLIC OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ME', 'MONTÉNÉGRO', 'MONTENEGRO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MF', 'SAINT-MARTIN', 'SAINT MARTIN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MG', 'MADAGASCAR', 'MADAGASCAR', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MH', 'MARSHALL, ÎLES', 'MARSHALL ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MK', 'MACÉDOINE, L''EX-RÉPUBLIQUE YOUGOSLAVE DE', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ML', 'MALI', 'MALI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MM', 'MYANMAR', 'MYANMAR', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MN', 'MONGOLIE', 'MONGOLIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MO', 'MACAO', 'MACAO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MP', 'MARIANNES DU NORD, ÎLES', 'NORTHERN MARIANA ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MQ', 'MARTINIQUE', 'MARTINIQUE', 0, 'D');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MR', 'MAURITANIE', 'MAURITANIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MS', 'MONTSERRAT', 'MONTSERRAT', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MT', 'MALTE', 'MALTA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MU', 'MAURICE', 'MAURITIUS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MV', 'MALDIVES', 'MALDIVES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MW', 'MALAWI', 'MALAWI', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MX', 'MEXIQUE', 'MEXICO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MY', 'MALAISIE', 'MALAYSIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('MZ', 'MOZAMBIQUE', 'MOZAMBIQUE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NA', 'NAMIBIE', 'NAMIBIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NC', 'NOUVELLE-CALÉDONIE', 'NEW CALEDONIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NE', 'NIGER', 'NIGER', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NF', 'NORFOLK, ÎLE', 'NORFOLK ISLAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NG', 'NIGÉRIA', 'NIGERIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NI', 'NICARAGUA', 'NICARAGUA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NL', 'PAYS-BAS', 'NETHERLANDS', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NO', 'NORVÈGE', 'NORWAY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NP', 'NÉPAL', 'NEPAL', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NR', 'NAURU', 'NAURU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NU', 'NIUÉ', 'NIUE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('NZ', 'NOUVELLE-ZÉLANDE', 'NEW ZEALAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('OM', 'OMAN', 'OMAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PA', 'PANAMA', 'PANAMA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PE', 'PÉROU', 'PERU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PF', 'POLYNÉSIE FRANÇAISE', 'FRENCH POLYNESIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PG', 'PAPOUASIE-NOUVELLE-GUINÉE', 'PAPUA NEW GUINEA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PH', 'PHILIPPINES', 'PHILIPPINES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PK', 'PAKISTAN', 'PAKISTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PL', 'POLOGNE', 'POLAND', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PM', 'SAINT-PIERRE-ET-MIQUELON', 'SAINT PIERRE AND MIQUELON', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PN', 'PITCAIRN', 'PITCAIRN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PR', 'PORTO RICO', 'PUERTO RICO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PS', 'PALESTINIEN OCCUPÉ, TERRITOIRE', 'PALESTINIAN TERRITORY, OCCUPIED', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PT', 'PORTUGAL', 'PORTUGAL', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PW', 'PALAOS', 'PALAU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('PY', 'PARAGUAY', 'PARAGUAY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('QA', 'QATAR', 'QATAR', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('RE', 'RÉUNION', 'REUNION', 0, 'D');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('RO', 'ROUMANIE', 'ROMANIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('RS', 'SERBIE', 'SERBIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('RU', 'RUSSIE, FÉDÉRATION DE', 'RUSSIAN FEDERATION', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('RW', 'RWANDA', 'RWANDA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SA', 'ARABIE SAOUDITE', 'SAUDI ARABIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SB', 'SALOMON, ÎLES', 'SOLOMON ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SC', 'SEYCHELLES', 'SEYCHELLES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SD', 'SOUDAN', 'SUDAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SE', 'SUÈDE', 'SWEDEN', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SG', 'SINGAPOUR', 'SINGAPORE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SH', 'SAINTE-HÉLÈNE', 'SAINT HELENA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SI', 'SLOVÉNIE', 'SLOVENIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SJ', 'SVALBARD ET ÎLE JAN MAYEN', 'SVALBARD AND JAN MAYEN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SK', 'SLOVAQUIE', 'SLOVAKIA', 1, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SL', 'SIERRA LEONE', 'SIERRA LEONE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SM', 'SAINT-MARIN', 'SAN MARINO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SN', 'SÉNÉGAL', 'SENEGAL', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SO', 'SOMALIE', 'SOMALIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SR', 'SURINAME', 'SURINAME', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ST', 'SAO TOMÉ-ET-PRINCIPE', 'SAO TOME AND PRINCIPE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SV', 'EL SALVADOR', 'EL SALVADOR', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SY', 'SYRIENNE, RÉPUBLIQUE ARABE', 'SYRIAN ARAB REPUBLIC', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('SZ', 'SWAZILAND', 'SWAZILAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TC', 'TURKS ET CAÏQUES, ÎLES', 'TURKS AND CAICOS ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TD', 'TCHAD', 'CHAD', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TF', 'TERRES AUSTRALES FRANÇAISES', 'FRENCH SOUTHERN TERRITORIES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TG', 'TOGO', 'TOGO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TH', 'THAÏLANDE', 'THAILAND', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TJ', 'TADJIKISTAN', 'TAJIKISTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TK', 'TOKELAU', 'TOKELAU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TL', 'TIMOR-LESTE', 'TIMOR-LESTE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TM', 'TURKMÉNISTAN', 'TURKMENISTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TN', 'TUNISIE', 'TUNISIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TO', 'TONGA', 'TONGA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TR', 'TURQUIE', 'TURKEY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TT', 'TRINITÉ-ET-TOBAGO', 'TRINIDAD AND TOBAGO', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TV', 'TUVALU', 'TUVALU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TW', 'TAÏWAN, PROVINCE DE CHINE', 'TAIWAN, PROVINCE OF CHINA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('TZ', 'TANZANIE, RÉPUBLIQUE-UNIE DE', 'TANZANIA, UNITED REPUBLIC OF', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('UA', 'UKRAINE', 'UKRAINE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('UG', 'OUGANDA', 'UGANDA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('UM', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS', 'UNITED STATES MINOR OUTLYING ISLANDS', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('US', 'ÉTATS-UNIS', 'UNITED STATES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('UY', 'URUGUAY', 'URUGUAY', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('UZ', 'OUZBÉKISTAN', 'UZBEKISTAN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VA', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)', 'HOLY SEE (VATICAN CITY STATE)', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VC', 'SAINT-VINCENT-ET-LES GRENADINES', 'SAINT VINCENT AND THE GRENADINES', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VE', 'VENEZUELA', 'VENEZUELA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VG', 'ÎLES VIERGES BRITANNIQUES', 'VIRGIN ISLANDS, BRITISH', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VI', 'ÎLES VIERGES DES ÉTATS-UNIS', 'VIRGIN ISLANDS, U.S.', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VN', 'VIET NAM', 'VIET NAM', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('VU', 'VANUATU', 'VANUATU', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('WF', 'WALLIS ET FUTUNA', 'WALLIS AND FUTUNA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('WS', 'SAMOA', 'SAMOA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('YE', 'YÉMEN', 'YEMEN', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('YT', 'MAYOTTE', 'MAYOTTE', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ZA', 'AFRIQUE DU SUD', 'SOUTH AFRICA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ZM', 'ZAMBIE', 'ZAMBIA', 0, '');
insert into PAYS (Code_Pays, Nom_FR, Nom_EN, Zone_UE, Type_Pays) values ('ZW', 'ZIMBABWE', 'ZIMBABWE', 0, '');
